### ISSUE TITLE
suggest moving comma to before "but"

### ISSUE THREAD

**Issue by Josh-Stillman** [learn-co-curriculum/oo-inheritance-code-along#18]
I suggest moving the comma to before "but."  

The sentence currently reads:

"Not only is it time consuming but, what happens when we need to make a change to this shared behavior?" 

I think it should read:

"Not only is it time consuming, but what happens when we need to make a change to this shared behavior?"

**Comment by curiositypaths** [comment]
Hi there,

We've updated the readme to reflect your suggestion.

As always, thanks for contributing! 💙
